import 'package:hh_example/common/widgets/theme_extensions.dart';
import 'package:hh_example/generated/colors.gen.dart';
import 'package:flutter/material.dart';

const colorsScheme = ColorsScheme(
  overlay: LinearGradient(
    colors: [
      ColorName.overlay1,
      ColorName.overlay2,
      ColorName.overlay3,
      ColorName.overlay4,
    ],
  ),
  textPrimary: ColorName.textPrimary,
  textSecondary: ColorName.textSecondary,
  textTertiary: ColorName.textTertiary,
  textSubhead: ColorName.textSubhead,
  textAccent: ColorName.textAccent,
  textNegative: ColorName.textNegative,
  textPositive: ColorName.textPositive,
  textLink: ColorName.textLink,
  backgroundPrimary: ColorName.backgroundPrimary,
  backgroundSecondary: ColorName.backgroundSecondary,
  backgroundTertiary: ColorName.backgroundTertiary,
  backgroundCard: ColorName.backgroundCard,
  backgroundField: ColorName.backgroundField,
  backgroundContrast: ColorName.backgroundContrast,
  backgroundAccent: ColorName.backgroundAccent,
  backgroundNegative: ColorName.backgroundNegative,
  backgroundPositive: ColorName.backgroundPositive,
  iconPrimary: ColorName.iconPrimary,
  iconSecondary: ColorName.iconSecondary,
  iconTertiary: ColorName.iconTertiary,
  iconContrastThemed: ColorName.iconContrastThemed,
  iconAccent: ColorName.iconAccent,
  iconAccentThemed: ColorName.iconAccentThemed,
  iconNegative: ColorName.iconNegative,
  iconPositive: ColorName.iconPositive,
  statesOverlay: ColorName.statesOverlay,
  statesPressAccentBG: ColorName.statesPressAccentBG,
  statesHoverAccentBG: ColorName.statesHoverAccentBG,
  statesDisablePrimaryText: ColorName.statesDisablePrimaryText,
  statesDisableAccent: ColorName.statesDisableAccent,
  statesLoad: ColorName.statesLoad,
  statesDisableBase: ColorName.statesDisableBase,
  statesPressBase: ColorName.statesPressBase,
  statesDisableIconPrimary: ColorName.statesDisableIconPrimary,
  statesDisableField: ColorName.statesDisableField,
  statesField: ColorName.statesField,
  statesPressField: ColorName.statesPressField,
  statesFocusField: ColorName.statesFocusField,
  statesHoverField: ColorName.statesHoverField,
  progress: ColorName.progress,
  white: ColorName.white,
  black: ColorName.black,
  bgUI: ColorName.bgUI,
  labelUI: ColorName.labelUI,
  separatorPrimary: ColorName.separatorPrimary,
  separatorPrimaryAlpha: ColorName.separatorPrimaryAlpha,
  separatorSecondary: ColorName.separatorSecondary,
  separatorAccent: ColorName.separatorAccent,
  separatorAccentThemed: ColorName.separatorAccentThemed,
  separatorNegative: ColorName.separatorNegative,
  separatorPositive: ColorName.separatorPositive,
);
