import 'package:hh_example/common/widgets/theme_extensions.dart';
import 'package:hh_example/generated/colors.gen.dart';
import 'package:hh_example/generated/fonts.gen.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

const defaultTextColor = ColorName.textPrimary;

final textThemes = TextThemes(
  hLM: () => TextStyle(
    fontFamily: FontFamily.golos,
    fontWeight: FontWeight.w500,
    fontSize: 32.sp,
    color: defaultTextColor,
    letterSpacing: .0,
    height: 40 / 32,
  ),
  hLS: () => TextStyle(
    fontFamily: FontFamily.golos,
    fontWeight: FontWeight.w600,
    fontSize: 32.sp,
    color: defaultTextColor,
    letterSpacing: .0,
    height: 40 / 32,
  ),
  hLB: () => TextStyle(
    fontFamily: FontFamily.golos,
    fontWeight: FontWeight.w700,
    fontSize: 32.sp,
    color: defaultTextColor,
    letterSpacing: .0,
    height: 40 / 32,
  ),
  hMR: () => TextStyle(
    fontFamily: FontFamily.golos,
    fontWeight: FontWeight.w400,
    fontSize: 28.sp,
    color: defaultTextColor,
    letterSpacing: -.45,
    height: 36 / 28,
  ),
  hMM: () => TextStyle(
    fontFamily: FontFamily.golos,
    fontWeight: FontWeight.w500,
    fontSize: 28.sp,
    color: defaultTextColor,
    letterSpacing: -.45,
    height: 36 / 28,
  ),
  hMS: () => TextStyle(
    fontFamily: FontFamily.golos,
    fontWeight: FontWeight.w600,
    fontSize: 28.sp,
    color: defaultTextColor,
    letterSpacing: -.45,
    height: 36 / 28,
  ),
  hSR: () => TextStyle(
    fontFamily: FontFamily.golos,
    fontWeight: FontWeight.w400,
    fontSize: 24.sp,
    color: defaultTextColor,
    letterSpacing: .48,
    height: 32 / 24,
  ),
  hSM: () => TextStyle(
    fontFamily: FontFamily.golos,
    fontWeight: FontWeight.w500,
    fontSize: 24.sp,
    color: defaultTextColor,
    letterSpacing: .48,
    height: 32 / 24,
  ),
  hSS: () => TextStyle(
    fontFamily: FontFamily.golos,
    fontWeight: FontWeight.w600,
    fontSize: 24.sp,
    color: defaultTextColor,
    letterSpacing: .48,
    height: 32 / 24,
  ),
  titleLR: () => TextStyle(
    fontFamily: FontFamily.golos,
    fontWeight: FontWeight.w400,
    fontSize: 18.sp,
    color: defaultTextColor,
    letterSpacing: .48,
    height: 28 / 18,
  ),
  titleLM: () => TextStyle(
    fontFamily: FontFamily.golos,
    fontWeight: FontWeight.w500,
    fontSize: 18.sp,
    color: defaultTextColor,
    letterSpacing: .48,
    height: 28 / 18,
  ),
  titleLS: () => TextStyle(
    fontFamily: FontFamily.golos,
    fontWeight: FontWeight.w600,
    fontSize: 18.sp,
    color: defaultTextColor,
    letterSpacing: .48,
    height: 28 / 18,
  ),
  titleLB: () => TextStyle(
    fontFamily: FontFamily.golos,
    fontWeight: FontWeight.w700,
    fontSize: 18.sp,
    color: defaultTextColor,
    letterSpacing: .48,
    height: 28 / 18,
  ),
  titleMR: () => TextStyle(
    fontFamily: FontFamily.golos,
    fontWeight: FontWeight.w400,
    fontSize: 16.sp,
    color: defaultTextColor,
    letterSpacing: -0.24,
    height: 24 / 16,
  ),
  titleMM: () => TextStyle(
    fontFamily: FontFamily.golos,
    fontWeight: FontWeight.w500,
    fontSize: 16.sp,
    color: defaultTextColor,
    letterSpacing: -0.24,
    height: 24 / 16,
  ),
  titleMS: () => TextStyle(
    fontFamily: FontFamily.golos,
    fontWeight: FontWeight.w600,
    fontSize: 16.sp,
    color: defaultTextColor,
    letterSpacing: -0.24,
    height: 24 / 16,
  ),
  titleSR: () => TextStyle(
    fontFamily: FontFamily.golos,
    fontWeight: FontWeight.w400,
    fontSize: 14.sp,
    color: defaultTextColor,
    letterSpacing: -.15,
    height: 20 / 14,
  ),
  titleSM: () => TextStyle(
    fontFamily: FontFamily.golos,
    fontWeight: FontWeight.w500,
    fontSize: 14.sp,
    color: defaultTextColor,
    letterSpacing: -.15,
    height: 20 / 14,
  ),
  titleSS: () => TextStyle(
    fontFamily: FontFamily.golos,
    fontWeight: FontWeight.w600,
    fontSize: 14.sp,
    color: defaultTextColor,
    letterSpacing: -.15,
    height: 20 / 14,
  ),
  titleSB: () => TextStyle(
    fontFamily: FontFamily.golos,
    fontWeight: FontWeight.w700,
    fontSize: 14.sp,
    color: defaultTextColor,
    letterSpacing: -.15,
    height: 20 / 14,
  ),
  bodyLR: () => TextStyle(
    fontFamily: FontFamily.golos,
    fontWeight: FontWeight.w400,
    fontSize: 16.sp,
    color: defaultTextColor,
    letterSpacing: -.16,
    height: 24 / 16,
  ),
  bodyLM: () => TextStyle(
    fontFamily: FontFamily.golos,
    fontWeight: FontWeight.w500,
    fontSize: 16.sp,
    color: defaultTextColor,
    letterSpacing: -.16,
    height: 24 / 16,
  ),
  bodyMR: () => TextStyle(
    fontFamily: FontFamily.golos,
    fontWeight: FontWeight.w400,
    fontSize: 14.sp,
    color: defaultTextColor,
    letterSpacing: -.16,
    height: 20 / 14,
  ),
  bodyMM: () => TextStyle(
    fontFamily: FontFamily.golos,
    fontWeight: FontWeight.w500,
    fontSize: 14.sp,
    color: defaultTextColor,
    letterSpacing: -.16,
    height: 20 / 14,
  ),
  labelLR: () => TextStyle(
    fontFamily: FontFamily.golos,
    fontWeight: FontWeight.w400,
    fontSize: 14.sp,
    color: defaultTextColor,
    letterSpacing: .1,
    height: 20 / 14,
  ),
  labelLM: () => TextStyle(
    fontFamily: FontFamily.golos,
    fontWeight: FontWeight.w500,
    fontSize: 14.sp,
    color: defaultTextColor,
    letterSpacing: .1,
    height: 20 / 14,
  ),
  labelLS: () => TextStyle(
    fontFamily: FontFamily.golos,
    fontWeight: FontWeight.w600,
    fontSize: 14.sp,
    color: defaultTextColor,
    letterSpacing: .1,
    height: 20 / 14,
  ),
  labelMR: () => TextStyle(
    fontFamily: FontFamily.golos,
    fontWeight: FontWeight.w400,
    fontSize: 12.sp,
    color: defaultTextColor,
    letterSpacing: .1,
    height: 16 / 12,
  ),
  labelMM: () => TextStyle(
    fontFamily: FontFamily.golos,
    fontWeight: FontWeight.w500,
    fontSize: 12.sp,
    color: defaultTextColor,
    letterSpacing: .1,
    height: 16 / 12,
  ),
  labelMS: () => TextStyle(
    fontFamily: FontFamily.golos,
    fontWeight: FontWeight.w600,
    fontSize: 12.sp,
    color: defaultTextColor,
    letterSpacing: .1,
    height: 16 / 12,
  ),
  labelSR: () => TextStyle(
    fontFamily: FontFamily.golos,
    fontWeight: FontWeight.w400,
    fontSize: 10.sp,
    color: defaultTextColor,
    letterSpacing: .2,
    height: 12 / 10,
  ),
  labelSM: () => TextStyle(
    fontFamily: FontFamily.golos,
    fontWeight: FontWeight.w500,
    fontSize: 10.sp,
    color: defaultTextColor,
    letterSpacing: .2,
    height: 12 / 10,
  ),
  labelSS: () => TextStyle(
    fontFamily: FontFamily.golos,
    fontWeight: FontWeight.w600,
    fontSize: 10.sp,
    color: defaultTextColor,
    letterSpacing: .2,
    height: 12 / 10,
  ),
);
