name: hh_example
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core
  async_task: ^1.1.1
  go_router: ^14.2.8
  hooks_riverpod: ^2.5.2
  flutter_hooks: ^0.20.5
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.5
  provider: ^6.1.2
  logger: ^2.4.0
  talker_dio_logger: ^4.4.0
  talker_flutter: ^4.4.0
  flutter_keyboard_visibility: ^6.0.0
  url_launcher: ^6.3.0
  collection: ^1.18.0
  fast_immutable_collections: ^11.0.0
  permission_handler: ^11.3.1
  flutter_svg: ^2.0.10+1
  easy_debounce: ^2.0.3
  sliver_tools: ^0.2.12
  skeletonizer: ^1.4.2
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.5
  package_info_plus: ^8.0.2
  encrypt: ^5.0.3

  # push services
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_analytics: ^11.3.3

  # Network, Data
  dio: ^5.6.0
  freezed_annotation: ^2.4.4
  encrypt_shared_preferences: ^0.8.0
  dart_pusher_channels: ^1.2.3

  # Other
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_screenutil: ^5.9.3
  modal_bottom_sheet: ^3.0.0
  reactive_forms: ^17.0.1
  wechat_assets_picker: ^9.2.1
  wechat_camera_picker: ^4.3.1
  wechat_picker_library: ^1.0.3
  el_tooltip: ^2.0.0
  animated_list_plus: ^0.5.2
  flutter_sticky_header: ^0.7.0
  flutter_widget_from_html: ^0.15.1
  map_launcher: ^3.5.0
  google_maps_flutter: ^2.9.0
  flutter_polyline_points: ^2.1.0
  geolocator: ^13.0.1
  google_geocoding_api: ^1.5.2
  pdf: ^3.11.1
  printing: ^5.13.3
  force_update_helper: ^0.1.5

  flutter_chat_bubble: ^2.0.2
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.15
  freshchat_sdk: ^0.10.23

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  go_router_builder: ^2.7.1
  custom_lint: ^0.7.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.2

dependency_overrides:
  rxdart: ^0.28.0


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Golos
      fonts:
        - asset: fonts/golos-text_bold.ttf
          weight: 700
        - asset: fonts/golos-text_demibold.ttf
          weight: 600
        - asset: fonts/golos-text_medium.ttf
          weight: 500
        - asset: fonts/golos-text_regular.ttf
          weight: 400

flutter_gen:
  output: lib/generated/
  line_length: 100

  integrations:
    image: true
    flutter_svg: true

  colors:
    inputs:
      - assets/color/colors.xml